"""Request/response contract shared with the iOS client (QuranAIModels.swift).

Keys are snake_case; the app decodes with `.convertFromSnakeCase`. Keep the two in sync.
"""
from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class ChatTurn(BaseModel):
    role: Literal["user", "assistant"]
    content: str = Field(max_length=4000)


ReadingMode = Literal["recite", "understand", "reflect", "custom"]


class AskRequest(BaseModel):
    question: str = Field(min_length=1, max_length=1000)
    # Recent turns for follow-up questions ("and how long is it held?").
    history: List[ChatTurn] = Field(default_factory=list, max_length=10)
    # Ayah shortcuts: the ayah the user picked and how they want to engage with it.
    # With these set, the ayah's verified text is always in the reference data.
    mode: Optional[ReadingMode] = None
    surah: Optional[int] = Field(default=None, ge=1, le=114)
    ayah: Optional[int] = Field(default=None, ge=1, le=286)


class PhoneticCard(BaseModel):
    """Structured pronunciation facts, rendered as a card in the app.

    Built deterministically from data/arabic_letters.json and data/tajweed_rules.json --
    never generated by the LLM -- so the makhraj shown is always the curated one.
    """
    kind: Literal["letter", "rule", "word"]
    arabic: str
    title: str
    transliteration: Optional[str] = None
    ipa: Optional[str] = None
    makhraj: Optional[str] = None
    characteristics: List[str] = Field(default_factory=list)
    description: str = ""
    tip: Optional[str] = None
    common_mistake: Optional[str] = None
    examples: List[str] = Field(default_factory=list)


class AyahReference(BaseModel):
    surah: int
    ayah: int
    surah_name: str
    arabic: str
    translation: str


class AskResponse(BaseModel):
    status: Literal["answered", "off_topic"]
    answer: str
    phonetics: List[PhoneticCard] = Field(default_factory=list)
    references: List[AyahReference] = Field(default_factory=list)
    model: str
